# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

def moengage_pods
  pod 'MoEngage-iOS-SDK', '~> 9.17.5'
  pod 'MoEngageInApp', '~> 6.0.3'
end

def firebase_pods
  pod 'Firebase/Auth', '~> 10.25'
  pod 'Firebase/Core', '~> 10.25'
  pod 'Firebase/Messaging', '~> 10.25'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig', '~> 10.25'
  pod 'Firebase/Crashlytics', '~> 10.25'
  pod 'Firebase/DynamicLinks', '~> 10.25'
  pod 'FirebaseAnalyticsOnDeviceConversion'
  pod 'FBSDKCoreKit', '~> 16.3'
end

target 'MobileFlutterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileFlutterDemo
  firebase_pods

  install_all_flutter_pods(flutter_application_path)

  target 'MobileFlutterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileFlutterDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
